home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.landing_page, name='landing_page'),
    path('login/', views.login, name='login'),
    path('registrole/', views.regist_role, name='regist_role'),
    path('registadmin/', views.regist_admin, name='regist_admin'),
    path('registdokter/', views.regist_dokter, name='regist_dokter'),
    path('registpenggunapublik/', views.regist_penggunapublik, name='regist_penggunapublik'),
    path('registsatgas/', views.regist_satgas, name='regist_satgas'),
    path('logout/', views.logout, name='logout'),
]

siruco/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trigger2.urls')),
    path('', include('home.urls')),
    path('',include(('transaksi_makan.urls'),namespace='transaksi_makan')),
    path('',include('trigger4.urls',namespace='trigger4')),
    path('', include('pasien.urls')),
    path('', include('trigger3.urls'))
]

transaksi_makan/urls.py
from django.urls import path
from django.contrib.auth import views
from . import views

app_name = 'transaksi_makanan'

urlpatterns = [
    path('transaksi_makan/paket_makan',views.list_paket_makan, name='paket_makan'),
    path('transaksi_makan/form_paket_makan',views.form_paket_makan, name='form_paket_makan'),
    path('transaksi_makan/delete_paket_makan/<str:kodehotel>/<str:kodepaket>', views.delete_paket_makan, name='delete_paket_makan'),
    path('transaksi_makan/<str:kodehotel>/<str:kodepaket>', views.update_paket_makan, name='update_paket_makan'),
    path('transaksi_makan/',views.list_transaksi_makan, name='transaksi_makan'),
]

transaksi_makan/models.py
from django.db import models

# Create your models here.

transaksi_makan/forms.py
from django import forms
from django.db import connection
from collections import namedtuple

class CreatePaketMakan(forms.Form):
    def get_id_hotel():
        cursor = connection.cursor()
        cursor.execute('set search_path to siruco;')
        cursor.execute('select kode from hotel;')
        response = cursor.fetchall()
        response2 = []
        for tup in response:
            response2.append((tup[0], tup[0]))
        cursor.close()

        return response2

    kode_hotel = forms.ChoiceField(label="Kode Hotel", choices= get_id_hotel())

    kode_paket2 = forms.CharField(label='Kode Paket', max_length=5, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tulis kode paket',
        'type' : 'text',
        'required': True,
    }))

    nama_paket = forms.CharField(label='Nama Paket', widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tulis kode paket',
        'type' : 'text',
        'required': True,
    }))

    harga = forms.IntegerField(label='Harga',required=True,widget=forms.NumberInput,min_value=0)

transaksi_makan/views.py
from django.shortcuts import render
from django.http import response
from django.shortcuts import render, redirect
from django.db import connection
from .forms import CreatePaketMakan
from collections import namedtuple
# Create your views here.

def namedtuplefetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return[dict(zip(columns, row)) for row in cursor.fetchall()]

def form_paket_makan(request):
    with connection.cursor() as cursor:
        response = {}
        response['error'] = False
        form = CreatePaketMakan(request.POST or None)
        response['form'] = form
        if request.method == 'POST':
            if form.is_valid():
                kode_hotel = request.POST.get('kode_hotel')
                kode_paket = request.POST.get('kode_paket2')
                nama_paket = request.POST.get('nama_paket')
                harga = request.POST.get('harga')
                cursor.execute("set search_path to siruco;")
                cursor.execute("INSERT INTO PAKET_MAKAN (kodehotel,kodepaket,nama,harga) VALUES ('{}','{}','{}','{}');".format(kode_hotel,kode_paket,nama_paket,harga))
                return redirect('transaksi_makan:paket_makan')
    form =  CreatePaketMakan()
    args = {
        'form' : form,
    }
    return render(request, 'form_paket_makan.html',args)

def list_paket_makan(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIRUCO;')
    cursor.execute('SELECT KodeHotel, KodePaket, nama, harga FROM PAKET_MAKAN;')
    list_paket_makan = cursor.fetchall()

    cursor.close()

    with connection.cursor() as cursor:
        cursor.execute("SELECT kodehotel, kodepaket, nama, harga FROM PAKET_MAKAN")
        all_paket_makan = namedtuplefetchall(cursor)
        kode_hotel = all_paket_makan[0]["kodehotel"]
        kode_paket =  all_paket_makan[0]["kodepaket"]
        nama =  all_paket_makan[0]["nama"]
        harga =  all_paket_makan[0]["harga"]

        args = {
            'list_paket_makan':list_paket_makan,
            'kode_hotel':kode_hotel,
            'kode_paket':kode_paket,
            'nama':nama,
            'harga':harga,
        }
        return render(request, 'paket_makan.html', args)

def delete_paket_makan(request,kodehotel,kodepaket):
    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM PAKET_MAKAN WHERE kodehotel ='{}' AND kodepaket ='{}';".format(kodehotel,kodepaket))
        return redirect('transaksi_makanan:paket_makan') 
    
def update_paket_makan(request,kodehotel,kodepaket):
    if request.method == 'POST':
        with connection.cursor() as cursor:
            nama = request.POST.get('nama')
            harga = request.POST.get('harga')
            cursor.execute("UPDATE PAKET_MAKAN SET kodeHotel ='{}', kodePaket ='{}', nama ='{}', harga ='{}' WHERE kodeHotel ='{}' AND kodePaket ='{}';".format(kodehotel,kodepaket,nama,harga,kodehotel,kodepaket))
            return redirect('transaksi_makan:paket_makan')

    with connection.cursor() as cursor:
        cursor.execute("SELECT * from PAKET_MAKAN WHERE kodehotel='{}' AND kodepaket='{}'".format(kodehotel, kodepaket))
        row = namedtuplefetchall(cursor)
        args = {
            'paket': row[0],
        }
    return render(request, 'update_paket_makan.html', args)

def list_transaksi_makan(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO SIRUCO;')
    cursor.execute('SELECT idtransaksi, idtransaksimakan, totalbayar FROM TRANSAKSI_MAKAN;')
    list_transaksi_makan = cursor.fetchall()

    cursor.close()

    with connection.cursor() as cursor:
        cursor.execute("SELECT idtransaksi, idtransaksimakan, totalbayar FROM TRANSAKSI_MAKAN;")
        all_transaksi_makan = namedtuplefetchall(cursor)
        idtransaksi = all_transaksi_makan[0]["idtransaksi"]
        idtransaksimakan =  all_transaksi_makan[0]["idtransaksimakan"]
        totalbayar =  all_transaksi_makan[0]["totalbayar"]

        args = {
            'list_transaksi_makan':list_transaksi_makan,
            'idtransaksi':idtransaksi,
            'idtransaksimakan':idtransaksimakan,
            'totalbayar':totalbayar,
        }
        return render(request, 'transaksi_makan.html', args)

transaksi_makan/templates/detail_transaksi_makan.html
{% extends 'home/base.html' %}
{% block content %}
{% include 'navbar.html' %}

<body>
    <div class="container">
        <h1 class="text-center">
            <b>Detail Transaksi Makan </b>
       </h1>
       <hr>
       <p>
           Id Transaksi :
           <br>
           Id Transaksi Makan :
           <br>
           Kode Hotel :
       </p>
       <p>
           Daftar Pesanan:
       </p>
       <table>
           <thead>
               <tr>
                   <th>Id Pesanan</th>
                   <th>Paket Makan</th>
                   <th>Harga</th>
               </tr>
           </thead>
           <tbody>
               <tr></tr>
           </tbody>
           Total: 
           <a class="text-center" href="#">KEMBALI</a>
       </table>
    </div>
</body>
{% endblock %}

transaksi_makan/templates/form_paket_makan.html
{% extends 'base.html' %} 
{% block content %}
{%load static%}
<body>
    <div class="container">
        <h1 class="text-center">Form Tambah Paket Makan</h1>
        <form action="{% url 'transaksi_makan:form_paket_makan' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label for="validationDefault01">Kode Hotel</label> {{ form.kode_hotel }}
            </div>
            <div class="form-group">
              <label for="validationDefault01">Kode Paket</label> {{ form.kode_paket2 }}
            </div>
            <div class="form-group">
              <label for="validationDefault01">Nama Paket</label> {{ form.nama_paket }}
            </div>
            <div class="form-group">
              <label for="validationDefault01">Harga</label> {{ form.harga }}
            </div>
            <input class="btn btn-primary" type="submit" value="Submit anyway">
        </form>
    </div>
</body>
{% endblock %}

transaksi_makan/templates/paket_makan.html
{% extends 'base.html' %} 
{% block content %}
{%load static%}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"crossorigin="anonymous"></script> 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src= "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"> </script>
<script src= "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> </script>
<body>

<h1 class='text-center'>List Paket Makan</h1>

<body>
    <div class='container'>
        <table class = 'table'>
            <thead class = 'thead-dark'>
                <tr>
                    <th>No</th>
                    <th>Hotel</th>
                    <th>Kode Paket</th>
                    <th>Nama Paket</th>
                    <th>Harga</th>
                    {% if request.session.type == 'adminSistem' %}
                    <th>Action</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for i in list_paket_makan %}
                <tr>
                    <th>{{forloop.counter}}</th>
                    <th>{{i.0}}</th>
                    <th>{{i.1}}</th>
                    <th>{{i.2}}</th>
                    <th>{{i.3}}</th>
                    {% if request.session.type == 'adminSistem' %}
                    <th>
                        <a class ="text-center" href="{% url 'transaksi_makan:update_paket_makan' kodehotel=i.0 kodepaket=i.1 %}">Update</a>
                        <br>
                        <a class ="text-center" href="{% url 'transaksi_makan:delete_paket_makan' kodehotel=i.0 kodepaket=i.1 %}">Delete</a>
                    </th>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <p class="text-center"><a class="text-center" href="{% url 'transaksi_makan:form_paket_makan' %}">CREATE PAKET MAKAN</a></p>
    </div>
</body>

</body>
{% endblock %}

transaksi_makan/templates/transaksi_makan.html
{% extends 'base.html' %} 
{% block content %}
{% include 'navbar.html' %}
<h1 class='text-center'> Data Transaksi Makan </h1>

<body>
    <div class='container text-center'>
        <table class="table">
            <thead class = 'thead-dark'>
                <tr>
                    <th>No</th>
                    <th>Id Transaksi Hotel</th>
                    <th>Id Transaksi</th>
                    <th>Total Bayar</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for i in list_transaksi_makan %}
                <tr>
                    <th>{{forloop.counter}}</th>
                    <th>{{i.0}}</th>
                    <th>{{i.1}}</th>
                    <th>{{i.2}}</th>
                    <th>
                        {% if request.session.type == 'adminSatgas' %}
                        <a class ="text-center" href="#">Update</a>
                        <br>
                        <a class ="text-center" href="#">Delete</a>
                        <br>
                        {% endif %}
                        <a class ="text-center" href="#">Detail</a>
                    </th>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <p class="text-center"><a class="text-center" href="#">CREATE TRANSAKSI MAKAN</a></p>
    </div>
</body>

{% endblock %}

transaksi_makan/templates/update_paket_makan.html
{% extends 'base.html' %} 
{% block content %}
{%load static%}

<body>
    <h1 class="text-center">Form Update Paket Makan</h1>
    <div class = "container">
    <form method="POST" action="{% url 'transaksi_makan:update_paket_makan' kodehotel=paket.kodehotel kodepaket=paket.kodepaket %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="kodehotel">Kode Hotel</label>
            <input class="form-control" id="kodehotel" name="kodehotel" type="text" disabled value={{paket.kodehotel}}>
        </div>
        <div class="form-group">
            <label for="kodepaket">Kode Paket</label>
            <input class="form-control" id="kodepaket" name="kodepaket" type="text" disabled value={{paket.kodepaket}}>
        </div>
        <div class="form-group">
            <label for="nama">Nama Paket</label>
            <input class="form-control" id="nama" name="nama" type="text" value='' required>
        </div>
        <div class="form-group">
            <label for="harga">Harga</label>
            <input class="form-control" id="harga" name="harga" type="text" value='' required>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
    </form>

</body>
{% endblock %}