home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.landing_page, name='landing_page'),
    path('login/', views.login, name='login'),
    path('registrole/', views.regist_role, name='regist_role'),
    path('registadmin/', views.regist_admin, name='regist_admin'),
    path('registdokter/', views.regist_dokter, name='regist_dokter'),
    path('registpenggunapublik/', views.regist_penggunapublik, name='regist_penggunapublik'),
    path('registsatgas/', views.regist_satgas, name='regist_satgas'),
    path('logout/', views.logout, name='logout'),
]

pasien/urls.py
from django.urls import path
from . import views

app_name = "pasien"

urlpatterns = [
    path('daftar/', views.daftar, name='daftar'),
    path('read/', views.read, name='read'),
    path('detail/<str:nik>', views.detail, name='detail'),
    path('delete/<str:nik>', views.delete, name='delete'),
    path('update/<str:nik>', views.update, name='update'),
]

siruco/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trigger2.urls')),
    path('', include('home.urls')),
    path('',include(('transaksi_makan.urls'),namespace='transaksi_makan')),
    path('',include('trigger4.urls',namespace='trigger4')),
    path('', include('pasien.urls')),
    path('', include('trigger3.urls'))
]

pasien/models.py
from django.db import models

# Create your models here.

pasien/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.sessions.models import Session
from django.db import connection
from django.db.utils import InternalError
from django.contrib import messages


def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def daftar(request):
    email = request.session['email']
    if request.method == 'POST':
        with connection.cursor() as cursor:
            nik = request.POST.get('nik')
            idpendaftar = email
            nama = request.POST.get('nama')
            kJalan = request.POST.get('ktp_jalan') 
            kKelurahan = request.POST.get('ktp_kelurahan')
            kKecamatan = request.POST.get('ktp_kecamatan')
            kKabKota = request.POST.get('ktp_kabkot')
            kProvinsi = request.POST.get('ktp_prov')
            dJalan = request.POST.get('dom_jalan')         
            dKelurahan = request.POST.get('dom_kelurahan')     
            dKecamatan = request.POST.get('dom_kecamatan')     
            dKabKota = request.POST.get('domk') 
            dProvinsi  = request.POST.get('dom_prov')  
            notelp = request.POST.get('notelp')
            nohp = request.POST.get('nohp')
            cursor.execute("SELECT nik FROM pasien WHERE nik=%s",[nik])
            a = cursor.fetchone()
            print(a)
            if a == None:
                cursor.execute("INSERT INTO pasien VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", 
                [nik, idpendaftar, nama, kJalan, kKelurahan, kKecamatan, kKabKota, kProvinsi, dJalan, dKelurahan, dKecamatan, dKabKota, dProvinsi, notelp, nohp])
                return redirect('pasien:read')
            else:
                messages.add_message(request, messages.WARNING, f"Pasien dengan nik tersebut telah terdaftar")
                return redirect("pasien:daftar")   
    context = {
        'email':email,
    }
    return render(request, 'daftar.html', context)

def read(request):
    email = request.session['email']
    maile = request.session['type']
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM pasien where idpendaftar =%s",[email])
        row = dictfetchall(cursor)
        context = {
            'lis': row,
        }
    return render(request, 'read.html', context)

def detail(request, nik):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM pasien where nik=%s",[nik])

        row = dictfetchall(cursor)
        context = {
            'row': row,
        }
    return render(request, 'detail.html', context)


def delete(request, nik):
    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM pasien where nik=%s",[nik])
        return redirect('pasien:read')

def update(request, nik):
    email = request.session['email']
    if request.method == 'POST':
        with connection.cursor() as cursor:
            nik = nik
            idpendaftar = email
            nama = request.POST.get('nama')
            kJalan = request.POST.get('ktp_jalan') 
            kKelurahan = request.POST.get('ktp_kelurahan')
            kKecamatan = request.POST.get('ktp_kecamatan')
            kKabKota = request.POST.get('ktp_kabkot')
            kProvinsi = request.POST.get('ktp_prov')
            dJalan = request.POST.get('dom_jalan')         
            dKelurahan = request.POST.get('dom_kelurahan')     
            dKecamatan = request.POST.get('dom_kecamatan')     
            dKabKota = request.POST.get('domk') 
            dProvinsi  = request.POST.get('dom_prov')  
            notelp = request.POST.get('notelp')
            nohp = request.POST.get('nohp') 
            cursor.execute("UPDATE pasien SET ktp_jalan=%s WHERE nik=%s", [kJalan, nik])
            cursor.execute("UPDATE pasien SET ktp_kelurahan=%s WHERE nik=%s", [kKelurahan, nik])
            cursor.execute("UPDATE pasien SET ktp_kecamatan=%s WHERE nik=%s", [kKecamatan, nik])
            cursor.execute("UPDATE pasien SET ktp_kabkot=%s WHERE nik=%s", [kKabKota, nik])
            cursor.execute("UPDATE pasien SET ktp_prov=%s WHERE nik=%s", [kProvinsi, nik])
            cursor.execute("UPDATE pasien SET dom_jalan=%s WHERE nik=%s", [dJalan, nik])
            cursor.execute("UPDATE pasien SET dom_kelurahan=%s WHERE nik=%s", [dKelurahan, nik])
            cursor.execute("UPDATE pasien SET dom_kecamatan=%s WHERE nik=%s", [dKecamatan, nik])
            cursor.execute("UPDATE pasien SET dom_kabkot=%s WHERE nik=%s", [dKabKota, nik])
            cursor.execute("UPDATE pasien SET dom_prov=%s WHERE nik=%s", [dProvinsi, nik])
            cursor.execute("UPDATE pasien SET notelp=%s WHERE nik=%s", [notelp, nik])
            cursor.execute("UPDATE pasien SET nohp=%s WHERE nik=%s", [nohp, nik])
            return redirect('pasien:read')

    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM pasien where nik=%s",[nik])
        row = dictfetchall(cursor)
        context = {
            'periksa':row[0],
            'email':email,
        }
        return render(request, 'update.html', context)

pasien/templates/daftar.html
{% extends "base.html" %} {%load static%} 
{% block content %}
<div class="container mt-5 pt-5 mb-5">
    <h2 style="text-align: center;">FORM DAFTAR PASIEN</h2>
    <form method="post" action="{% url 'pasien:daftar' %}">
        {% csrf_token %}

        {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}} fade show" role="alert">
            {{message}}
          </div>
        {% endfor %}
        {% endif %}

        <div class="form-group">
            <label for="idpendaftar" >Pendaftar</label>
            <input class="form-control" name="idpendaftar" id="idpendaftar" type="text" disabled value={{email}}>
        </div>
        <div class="form-group">
            <label for="nik" >NIK</label>
            <input class="form-control" name="nik" id="nik" type="text" value='' required>
        </div>
        <div class="form-group">
            <label for="nama" >Nama</label>
            <input class="form-control" name = "nama" id="nama" type="text" value='' required>
        </div>
        <div class="form-group">
            <label for="notelp" >Nomor Telepon</label>
            <input class="form-control" name="notelp" id="notelp" type="text" value='' required>
        </div>
        <div class="form-group">
            <label for="nohp" >Nomor Hp</label>
            <input class="form-control" name="nohp" id="nohp" type="text" value='' required>
        </div>
        <div class="form-group">
            <label for="alamat">Alamat(Sesuai KTP)</label>
            <label for="ktp_jalan" >Jalan</label>
            <input class="form-control" name="ktp_jalan" id="ktp_jalan" type="text" value='' required>
        </div>
        <div class="form-group">
            <label for="ktp_kelurahan" >Kelurahan </label>
            <input class="form-control" name="ktp_kelurahan" id="ktp_kelurahan" type="text" value='' required>
        </div>
        <div class="form-group">
            <label for="ktp_kecamatan">Kecamatan</label>
            <input class="form-control" name="ktp_kecamatan" id="ktp_kecamatan" type="text" value='' required>
        </div>
        <div class="form-group">
            <label for="ktp_kabkot" >Kabupaten/Kota</label>
            <input class="form-control" name="ktp_kabkot" id="ktp_kabkot" type="text" value='' required>
        </div>
        <div class="form-group">
            <label for="ktp_prov">Provinsi</label>
            <input class="form-control" name="ktp_prov" id="ktp_prov" type="text" value='' required>
        </div>
        <div class="form-group">
            <label  >Alamat(Domisili)</label>
            <label for="dom_jalan">Jalan</label>
            <input class="form-control" name="dom_jalan" id="dom_jalan" type="text" value='' required>
        </div>
        <div class="form-group">
            <label for="dom_kelurahan">Kelurahan </label>
            <input class="form-control" name="dom_kelurahan" id="dom_kelurahan" type="text" value='' required>
        </div>
        <div class="form-group">
            <label for="dom_kecamatan">Kecamatan</label>
            <input class="form-control" name="dom_kecamatan" id="dom_kecamatan" type="text" value='' required>
        </div>
        <div class="form-group">
            <label for="domk">Kabupaten/Kota</label>
            <input class="form-control" name="domk" id="domk" type="text" value='' required>
        </div>
        <div class="form-group">
            <label for="dom_prov">Provinsi</label>
            <input class="form-control" name="dom_prov" id="dom_prov" type="text" value='' required>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock content %}

pasien/templates/detail.html
{% extends "base.html" %} {%load static%} 
{% block content %}
<div class="container mt-5 pt-5 mb-5">
    <h2 style="text-align: center;">Detail Pasien</h2>
    <br>
    {%for lis in row%}
        <p>Pendaftar           :{{lis.idpendaftar}}</p>
        <p>NIK                 :{{lis.nik}}</p>
        <p>Nama                :{{lis.nama}}</p>
        <p>Nomor Telepon       :{{lis.notelp}}</p>
        <p>Nomor Hp            :{{lis.nohp}}</p>
        <p>Alamat(Sesuai KTP)  :</p>
        <p>Jalan           :{{lis.ktp_jalan}}</p>
        <p>Kelurahan       :{{lis.ktp_kelurahan}}</p>
        <p>Kecamatan       :{{lis.ktp_kecamatan}}</p>
        <p>Kabupaten/Kota  :{{lis.ktp_kabkot}}</p>
        <p>Provinsi        :{{lis.ktp_prov}}</p>
        <p>Alamat(Domisili)    :</p>
        <p>Jalan           :{{lis.dom_jalan}}</p>
        <p>Kelurahan       :{{lis.dom_kelurahan}}</p>
        <p>Kecamatan       :{{lis.dom_kecamatan}}</p>
        <p>Kabupaten/Kota  :{{lis.dom_kabkot}}</p>
        <p>Provinsi        :{{lis.dom_prov}}</p>
    {% endfor %}
    <a href="{% url 'pasien:read' %}">
        <button class="btn btn-outline-primary">Back</button>
    </a>
</div>
{% endblock content %}

pasien/templates/read.html
{% extends "base.html" %} {%load static%} 
{% block content %}
<div class="container mt-5 pt-5 mb-5">
  <h2>List Pasien</h2>
  <br />
  <table class="table">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">NIK</th>
        <th scope="col">Nama Pasien</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {%for row in lis%}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{row.nik}}</td>
        <td>{{row.nama}}</td>
        <td> 
          <a href="{% url 'pasien:update' nik=row.nik %}">
            <button class="btn btn-outline-primary">Update</button>
          </a>
          <a href="{% url 'pasien:delete' nik=row.nik %}">
            <button class="btn btn-outline-danger">Delete</button>
          </a>
          <a href="{% url 'pasien:detail' nik=row.nik %}">
            <button class="btn btn-outline-primary">Detail</button>
          </a>
        </td>
      </tr>
      {%endfor%}
    </tbody>
  </table>
</div>
{% endblock content %}

pasien/templates/update.html
{% extends "base.html" %} {%load static%} 
{% block content %}
<div class="container mt-5 pt-5 mb-5">
    <h2 style="text-align: center;">FORM UPDATE PASIEN</h2>
    <form method="post" action="{% url 'pasien:update' nik=periksa.nik %}">
        {% csrf_token %}

        <div class="form-group">
            <label for="idpendaftar" >Pendaftar</label>
            <input class="form-control" name="idpendaftar" id="idpendaftar" type="text" disabled value={{email}}>
        </div>
        <div class="form-group">
            <label for="nik" >NIK</label>
            <input class="form-control" name="nik" id="nik" type="text" value='{{periksa.nik}}' disabled required>
        </div>
        <div class="form-group">
            <label for="nama" >Nama</label>
            <input class="form-control" name = "nama" id="nama" type="text" value='{{periksa.nama}}' disabled required>
        </div>
        <div class="form-group">
            <label for="notelp" >Nomor Telepon</label>
            <input class="form-control" name="notelp" id="notelp" type="text" value='{{periksa.notelp}}' required>
        </div>
        <div class="form-group">
            <label for="nohp" >Nomor Hp</label>
            <input class="form-control" name="nohp" id="nohp" type="text" value='{{periksa.nohp}}' required>
        </div>
        <div class="form-group">
            <label for="alamat">Alamat(Sesuai KTP)</label>
            <label for="ktp_jalan" >Jalan</label>
            <input class="form-control" name="ktp_jalan" id="ktp_jalan" type="text" value='{{periksa.ktp_jalan}}' required>
        </div>
        <div class="form-group">
            <label for="ktp_kelurahan" >Kelurahan </label>
            <input class="form-control" name="ktp_kelurahan" id="ktp_kelurahan" type="text" value='{{periksa.ktp_kelurahan}}' required>
        </div>
        <div class="form-group">
            <label for="ktp_kecamatan">Kecamatan</label>
            <input class="form-control" name="ktp_kecamatan" id="ktp_kecamatan" type="text" value='{{periksa.ktp_kecamatan}}' required>
        </div>
        <div class="form-group">
            <label for="ktp_kabkot" >Kabupaten/Kota</label>
            <input class="form-control" name="ktp_kabkot" id="ktp_kabkot" type="text" value='{{periksa.ktp_kabkot}}' required>
        </div>
        <div class="form-group">
            <label for="ktp_prov">Provinsi</label>
            <input class="form-control" name="ktp_prov" id="ktp_prov" type="text" value='{{periksa.ktp_prov}}' required>
        </div>
        <div class="form-group">
            <label  >Alamat(Domisili)</label>
            <label for="dom_jalan">Jalan</label>
            <input class="form-control" name="dom_jalan" id="dom_jalan" type="text" value='{{periksa.dom_jalan}}' required>
        </div>
        <div class="form-group">
            <label for="dom_kelurahan">Kelurahan </label>
            <input class="form-control" name="dom_kelurahan" id="dom_kelurahan" type="text" value='{{periksa.dom_kelurahan}}' required>
        </div>
        <div class="form-group">
            <label for="dom_kecamatan">Kecamatan</label>
            <input class="form-control" name="dom_kecamatan" id="dom_kecamatan" type="text" value='{{periksa.dom_kecamatan}}' required>
        </div>
        <div class="form-group">
            <label for="domk">Kabupaten/Kota</label>
            <input class="form-control" name="domk" id="domk" type="text" value='{{periksa.dom_kabkot}}' required>
        </div>
        <div class="form-group">
            <label for="dom_prov">Provinsi</label>
            <input class="form-control" name="dom_prov" id="dom_prov" type="text" value='{{periksa.dom_prov}}' required>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock content %}