home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.landing_page, name='landing_page'),
    path('login/', views.login, name='login'),
    path('registrole/', views.regist_role, name='regist_role'),
    path('registadmin/', views.regist_admin, name='regist_admin'),
    path('registdokter/', views.regist_dokter, name='regist_dokter'),
    path('registpenggunapublik/', views.regist_penggunapublik, name='regist_penggunapublik'),
    path('registsatgas/', views.regist_satgas, name='regist_satgas'),
    path('logout/', views.logout, name='logout'),
]

pasien/urls.py
from django.urls import path
from . import views

app_name = "pasien"

urlpatterns = [
    path('daftar/', views.daftar, name='daftar'),
    path('read/', views.read, name='read'),
    path('detail/<str:nik>', views.detail, name='detail'),
    path('delete/<str:nik>', views.delete, name='delete'),
    path('update/<str:nik>', views.update, name='update'),
]

siruco/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trigger2.urls')),
    path('', include('home.urls')),
    path('',include(('transaksi_makan.urls'),namespace='transaksi_makan')),
    path('',include('trigger4.urls',namespace='trigger4')),
    path('', include('pasien.urls')),
    path('', include('trigger3.urls'))
]

transaksi_makan/urls.py
from django.urls import path
from django.contrib.auth import views
from . import views

app_name = 'transaksi_makanan'

urlpatterns = [
    path('transaksi_makan/paket_makan',views.list_paket_makan, name='paket_makan'),
    path('transaksi_makan/form_paket_makan',views.form_paket_makan, name='form_paket_makan'),
    path('transaksi_makan/delete_paket_makan/<str:kodehotel>/<str:kodepaket>', views.delete_paket_makan, name='delete_paket_makan'),
    path('transaksi_makan/<str:kodehotel>/<str:kodepaket>', views.update_paket_makan, name='update_paket_makan'),
    path('transaksi_makan/',views.list_transaksi_makan, name='transaksi_makan'),
]

trigger2/urls.py
from django.urls import path
from . import views

app_name = "trigger2"

urlpatterns = [
    path('createjadwalDokter/', views.createJadwalDokter, name='createJadwalDokter'),
    path('createjadwal/<str:kode_faskes>/<str:shift>/<str:tanggal>', views.createJadwal, name='createJadwal'),
    path('listjadwalDokter/', views.readJadwalDokter, name='readJadwalDokter'),
    path('listappointment/', views.listAppointment, name='listAppointment'),
    path('listruanganRS/', views.listRuanganRS, name='listRuanganRS'),
    path('updateruanganRS/<str:koders>/<str:koderuangan>', views.updateRuanganRS, name='updateRuanganRS'),
    path('listbedRS/', views.listBedRs, name='listBedRs'),
    path('deletebedRS/<str:koders>/<str:koderuangan>/<str:kodebed>', views.deleteBedRS, name='deleteBedRS'),
    path('updateappointment/<str:nik_pasien>/<str:nostr>/<str:username_dokter>/<str:kode_faskes>/<str:praktek_shift>/<str:praktek_tgl>', views.updateappointment, name='updateappointment'),
    path('deleteappointment/<str:nik_pasien>/<str:nostr>/<str:username_dokter>/<str:kode_faskes>/<str:praktek_shift>/<str:praktek_tgl>', views.deleteappointment, name='deleteappointment'),
    path('createBedRS/', views.createBedRS, name='createBedRS'),
    path('createRuanganRS/', views.createRuanganRS, name='createRuanganRS'),
    path('createAppointment/', views.createappointment, name='createappointment'),
    path('buatappointment/<str:nostr>/<str:username_dokter>/<str:kode_faskes>/<str:praktek_shift>/<str:praktek_tgl>', views.buatappointment, name='buatappointment'),
    path('ruang/<str:koders>', views.ruang, name='ruang'),
    path('createBedRS/', views.createBedRS, name='createBedRS'),
    path('bed/', views.createbed, name='createbed'),
    path('bedX/', views.bed, name='bed'),
    path('hasilruang/<str:koders>/<str:koderuangan>', views.hasilruang, name='hasilruang'),
]

trigger4/urls.py
from django.urls import path
from . import views

app_name = 'trigger4'

urlpatterns = [
    path('create-ruangan-hotel/', views.create_ruangan_hotel, name='create_ruangan_hotel'),
    path('read-ruangan-hotel/', views.read_ruangan_hotel, name='read_ruangan_hotel'),
    path('update-ruangan-hotel/<str:koderoom>', views.update_ruangan_hotel, name='update_ruangan_hotel'),
    path('delete-ruangan-hotel/<str:koderoom>', views.delete_ruangan_hotel, name='delete_ruangan_hotel'),
    path('create-reservasi-hotel/', views.create_reservasi_hotel, name='create_reservasi_hotel'),
    path('read-reservasi-hotel/', views.read_reservasi_hotel, name='read_reservasi_hotel'),
    path('read-transaksi-hotel/', views.read_transaksi_hotel, name='read_transaksi_hotel'),
]

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS jQuery-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>SIRUCO</title>
</head>
<body class="mt-5">
    {% include "navbar.html" %}
    {% block content %}
    {% endblock content %}  
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"crossorigin="anonymous"></script> 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src= "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"> </script>
    <script src= "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> </script> -->

    <!-- <script src="{% static 'js/bed.js' %}"></script> -->
</body>
</html>

templates/navbar.html
{%load static%}
<nav class="navbar fixed-top navbar-expand-lg navbar-light" style="background-color: #86c8ee;">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home:landing_page' %}">SIRUCO</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
            <!-- role admin sistem -->
            {% if request.session.type == 'adminSistem' %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Hotel
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Create Hotel</a>
                    <a class="dropdown-item" href="#">List Hotel</a>
                    <a class="dropdown-item" href="{% url 'trigger4:create_ruangan_hotel' %}">Create Ruangan Hotel</a>
                    <a class="dropdown-item" href="{% url 'trigger4:read_ruangan_hotel' %}">List Ruangan Hotel</a>
                    <a class="dropdown-item" href="{% url 'transaksi_makan:form_paket_makan' %}">Create Paket Makan</a>
                    <a class="dropdown-item" href="{% url 'transaksi_makan:paket_makan' %}">List Paket Makan</a>
                </div>
            </li>
            <li class="nav-item">
                <a href="{% url 'home:logout' %}" class="nav-link">Logout</a>
            </li>
            {% endif %}
            <!-- role pengguna publik-->
            {% if request.session.type == 'penggunaPublik' %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Pasien
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'pasien:daftar' %}">Pendaftaran Pasien</a>
                    <a class="dropdown-item" href="{% url 'pasien:read' %}">List Pasien</a>
                    <a class="dropdown-item" href="{% url 'trigger2:createappointment' %}">Create Appointment</a>
                    <a class="dropdown-item" href="{% url 'trigger2:listAppointment' %}">List Appointment</a>
                    <a class="dropdown-item" href="#">Create Hasil Tes Pasien</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Rumah Sakit
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'trigger2:readJadwalDokter' %}">List Jadwal Dokter</a>
                    <a class="dropdown-item" href="#">List Reservasi RS</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Hotel
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">List Hotel</a>
                    <a class="dropdown-item" href="{% url 'trigger4:read_ruangan_hotel' %}">List Ruangan Hotel</a>
                    <a class="dropdown-item" href="#">List Paket Makan</a>
                    <a class="dropdown-item" href="#">Create Reservasi Hotel</a>
                    <a class="dropdown-item" href="{% url 'trigger4:read_reservasi_hotel' %}">List Reservasi Hotel</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Transaksi
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Bayar Transaksi RS</a>
                    <a class="dropdown-item" href="#">Bayar Transaksi Hotel</a>
                    <a class="dropdown-item" href="{% url 'trigger4:read_transaksi_hotel' %}">List Transaksi Booking Hotel</a>
                    <a class="dropdown-item" href="#">Create Transaksi Makan dan Daftar Pesan</a>
                    <a class="dropdown-item" href="#">List Transaksi Makan dan Daftar Pesan</a>
                </div>
            </li>
            <li class="nav-item">
                <a href="{% url 'home:logout' %}" class="nav-link">Logout</a>
            </li>
            {% endif %}
            <!-- role dokter-->
            {% if request.session.type == 'dokter' %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Pasien
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'trigger2:listAppointment' %}">List Appointment</a>
                    <a class="dropdown-item" href="#">Create Hasil Tes Pasien</a>
                    <a class="dropdown-item" href="#">List Hasil Tes Pasien</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Rumah Sakit
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'trigger2:createJadwalDokter' %}">Create Jadwal Dokter</a>
                    <a class="dropdown-item" href="{% url 'trigger2:readJadwalDokter' %}">List Jadwal Dokter</a>
                </div>
            </li>
            <li class="nav-item">
                <a href="{% url 'home:logout' %}" class="nav-link">Logout</a>
            </li>
            {% endif %}
            <!-- role admin satgas-->
            {% if request.session.type == 'adminSatgas' %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Pasien
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'trigger2:createappointment' %}">Create Appointment</a>
                    <a class="dropdown-item" href="{% url 'trigger2:listAppointment' %}">List Appointment</a>
                    <a class="dropdown-item" href="#">List Hasil Tes Pasien</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Faskes
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Create Faskes</a>
                    <a class="dropdown-item" href="#">List Faskes</a>
                    <a class="dropdown-item" href="#">Create Jadwal Faskes</a>
                    <a class="dropdown-item" href="#">List Jadwal Faskes</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Rumah Sakit
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Create RS</a>
                    <a class="dropdown-item" href="#">List RS</a>
                    <a class="dropdown-item" href="{% url 'trigger2:readJadwalDokter' %}">List Jadwal Dokter</a>
                    <a class="dropdown-item" href="{% url 'trigger2:createRuanganRS' %}">Create Ruangan RS</a>
                    <a class="dropdown-item" href="{% url 'trigger2:listRuanganRS' %}">List Ruangan RS</a>
                    <a class="dropdown-item" href="{% url 'trigger2:createBedRS' %}">Create Bed RS</a>
                    <a class="dropdown-item" href="{% url 'trigger2:listBedRs' %}">List Bed RS</a>
                    <a class="dropdown-item" href="#">Create Reservasi RS</a>
                    <a class="dropdown-item" href="#">List Reservasi RS</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Hotel
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">List Hotel</a>
                    <a class="dropdown-item" href="{% url 'trigger4:read_ruangan_hotel' %}">List Ruangan Hotel</a>
                    <a class="dropdown-item" href="#">List Paket Makan</a>
                    <a class="dropdown-item" href="#">Create Reservasi Hotel</a>
                    <a class="dropdown-item" href="{% url 'trigger4:read_reservasi_hotel' %}">List Reservasi Hotel</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Transaksi
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">List Transaksi RS</a>
                    <a class="dropdown-item" href="#">List Transaksi Hotel</a>
                    <a class="dropdown-item" href="{% url 'trigger4:read_transaksi_hotel' %}">List Transaksi Booking Hotel</a>
                    <a class="dropdown-item" href="#">Create Transaksi Makan dan Daftar Pesan</a>
                    <a class="dropdown-item" href="#">List Transaksi Makan dan Daftar Pesan</a>
                </div>
            </li>
            <li class="nav-item">
                <a href="{% url 'home:logout' %}" class="nav-link">Logout</a>
            </li>
            {% endif %}
            </ul>
        </div>
    </div>
</nav>