home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.landing_page, name='landing_page'),
    path('login/', views.login, name='login'),
    path('registrole/', views.regist_role, name='regist_role'),
    path('registadmin/', views.regist_admin, name='regist_admin'),
    path('registdokter/', views.regist_dokter, name='regist_dokter'),
    path('registpenggunapublik/', views.regist_penggunapublik, name='regist_penggunapublik'),
    path('registsatgas/', views.regist_satgas, name='regist_satgas'),
    path('logout/', views.logout, name='logout'),
]

siruco/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trigger2.urls')),
    path('', include('home.urls')),
    path('',include(('transaksi_makan.urls'),namespace='transaksi_makan')),
    path('',include('trigger4.urls',namespace='trigger4')),
    path('', include('pasien.urls')),
    path('', include('trigger3.urls'))
]

trigger2/urls.py
from django.urls import path
from . import views

app_name = "trigger2"

urlpatterns = [
    path('createjadwalDokter/', views.createJadwalDokter, name='createJadwalDokter'),
    path('createjadwal/<str:kode_faskes>/<str:shift>/<str:tanggal>', views.createJadwal, name='createJadwal'),
    path('listjadwalDokter/', views.readJadwalDokter, name='readJadwalDokter'),
    path('listappointment/', views.listAppointment, name='listAppointment'),
    path('listruanganRS/', views.listRuanganRS, name='listRuanganRS'),
    path('updateruanganRS/<str:koders>/<str:koderuangan>', views.updateRuanganRS, name='updateRuanganRS'),
    path('listbedRS/', views.listBedRs, name='listBedRs'),
    path('deletebedRS/<str:koders>/<str:koderuangan>/<str:kodebed>', views.deleteBedRS, name='deleteBedRS'),
    path('updateappointment/<str:nik_pasien>/<str:nostr>/<str:username_dokter>/<str:kode_faskes>/<str:praktek_shift>/<str:praktek_tgl>', views.updateappointment, name='updateappointment'),
    path('deleteappointment/<str:nik_pasien>/<str:nostr>/<str:username_dokter>/<str:kode_faskes>/<str:praktek_shift>/<str:praktek_tgl>', views.deleteappointment, name='deleteappointment'),
    path('createBedRS/', views.createBedRS, name='createBedRS'),
    path('createRuanganRS/', views.createRuanganRS, name='createRuanganRS'),
    path('createAppointment/', views.createappointment, name='createappointment'),
    path('buatappointment/<str:nostr>/<str:username_dokter>/<str:kode_faskes>/<str:praktek_shift>/<str:praktek_tgl>', views.buatappointment, name='buatappointment'),
    path('ruang/<str:koders>', views.ruang, name='ruang'),
    path('createBedRS/', views.createBedRS, name='createBedRS'),
    path('bed/', views.createbed, name='createbed'),
    path('bedX/', views.bed, name='bed'),
    path('hasilruang/<str:koders>/<str:koderuangan>', views.hasilruang, name='hasilruang'),
]

trigger2/models.py
from django.db import models

# Create your models here.

trigger2/forms.py
from django import forms
from django.db import connection

class CreateRuanganForm(forms.Form):
    def __init__(self, kode_choices=None, *args, **kwargs):
        super(CreateRuanganForm, self).__init__(*args, **kwargs)
        self.fields['kode'].choices = kode_choices

    kode = forms.ChoiceField(label='Kode:', required=True, choices=())

class PasienForm(forms.Form):
    def __init__(self, kode_choices=None, *args, **kwargs):
        super(PasienForm, self).__init__(*args, **kwargs)
        self.fields['kode'].choices = kode_choices

    kode = forms.ChoiceField(label='kode', required=True, choices=())

class ChooseRsForm(forms.Form):
    def __init__(self, kode_choices=None, *args, **kwargs):
        super(ChooseRsForm, self).__init__(*args, **kwargs)
        self.fields['kode'].choices = kode_choices

    kode = forms.ChoiceField(label='Kode:', required=True, choices=())

trigger2/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.sessions.models import Session
from django.db import connection
from .forms import CreateRuanganForm, PasienForm, ChooseRsForm
from django.db.utils import InternalError, IntegrityError
from django.contrib import messages


# Create your views here.

def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

#nomor 4
def createJadwalDokter(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM jadwal")
        row = dictfetchall(cursor)
        context = {
            'jadwal': row,
        }
        return render(request, 'createJadwalDokter.html', context)

def createJadwal(request, kode_faskes, shift, tanggal):
    email = request.session['email']
    orang = request.session['type']
    with connection.cursor() as cursor:
        #select dokter sesuai nama dokter yg sedang akses
        cursor.execute("SELECT username FROM dokter where username =%s",[email])
        nama = cursor.fetchone()
        n = nama[0]
        cursor.execute("SELECT nostr FROM dokter where username =%s",[email])
        str = cursor.fetchone()
        s = str[0]
        cursor.execute("select * from jadwal_dokter where nostr=%s and username=%s and kode_faskes=%s and shift=%s and tanggal=%s",[s, n, kode_faskes, shift, tanggal])
        row = cursor.fetchone()
        print(row)
        if row == None: 
            cursor.execute("INSERT INTO jadwal_dokter VALUES(%s, %s, %s, %s, %s, '0')",[s, n, kode_faskes, shift, tanggal])
            return redirect("trigger2:readJadwalDokter")
        else:
            return redirect("trigger2:readJadwalDokter")

def readJadwalDokter(request):
    email = request.session['email']
    maile = request.session['type']
    with connection.cursor() as cursor:
        if maile == 'penggunaPublik' or maile == 'adminSatgas':
            cursor.execute("SELECT * FROM jadwal_dokter")
        else:
            cursor.execute("SELECT * FROM jadwal_dokter where username =%s",[email])

        row = dictfetchall(cursor)
        context = {
            'list_jadwal': row,
        }
    return render(request, 'readJadwalDokter.html', context)

#nomor 5
def createappointment(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM jadwal_dokter")
        row = dictfetchall(cursor)
        context = {
            'jadwal': row,
        }
        return render(request, 'createAppointment.html', context)

def buatappointment(request, nostr, username_dokter, kode_faskes, praktek_tgl, praktek_shift):
    email = request.session['email']
    orang = request.session['type']
    with connection.cursor() as cursor:
        #pembuat admin satgas
        if orang == 'adminSatgas':
            cursor.execute("SELECT * FROM pasien")
        #pembuat si pengguna publik
        if orang == 'penggunaPublik':
            cursor.execute("SELECT * FROM pasien where idpendaftar =%s",[email])

        choice =  [(_[0], _[0]) for _ in cursor.fetchall()]
        cursor.execute("SELECT * FROM jadwal_dokter where nostr=%s and username=%s and kode_faskes=%s and tanggal=%s and shift=%s",[nostr, username_dokter, kode_faskes, praktek_tgl, praktek_shift])
        row = dictfetchall(cursor)

        if request.method == 'POST':
            data = request.POST.get('koders')
            try:
                cursor.execute("INSERT INTO memeriksa VALUES(%s, %s, %s, %s, %s, %s)",
                [ data, nostr, username_dokter, kode_faskes, praktek_shift, praktek_tgl])
                return redirect("trigger2:listAppointment")
            except InternalError:
                messages.add_message(request, messages.WARNING, f"Silahkan pilih shift dan tanggal lainnya, karena shift dan tanggal yang dipilih sudah penuh")
                return redirect("trigger2:createappointment")
        else:
            form = PasienForm(choice)
            context = {
                'periksa': row[0],
                'form' : form,
            }
            return render(request, 'buatAppointment.html', context)

def listAppointment(request):
    email = request.session['email']
    orang = request.session['type']
    with connection.cursor() as cursor:
        if orang == 'dokter':
            cursor.execute("SELECT * FROM memeriksa where username_dokter =%s",[email]) 
        elif orang == 'adminSatgas':
            cursor.execute("SELECT * FROM memeriksa")
        elif orang == 'penggunaPublik':
            cursor.execute("SELECT nik FROM pasien where idpendaftar=%s",[email])
            str = cursor.fetchone()
            s = str[0]
            cursor.execute("SELECT * FROM memeriksa where nik_pasien=%s",[str])
        row = dictfetchall(cursor)
        context = {
            'list_periksa': row,
        }
        return render(request, 'listAppointment.html', context)

def updateappointment(request, nik_pasien, nostr, username_dokter, kode_faskes, praktek_shift, praktek_tgl):
    if request.method == 'POST':
        with connection.cursor() as cursor:
            rekomendasi = request.POST.get('rekomendasi')
            cursor.execute("UPDATE memeriksa SET rekomendasi=%s WHERE nik_pasien=%s AND nostr=%s AND username_dokter=%s AND kode_faskes=%s AND praktek_shift=%s AND praktek_tgl=%s", [rekomendasi, nik_pasien, nostr, username_dokter, kode_faskes, praktek_shift, praktek_tgl])
            return redirect('trigger2:listAppointment')

    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM memeriksa WHERE nik_pasien=%s AND nostr=%s AND username_dokter=%s AND kode_faskes=%s AND praktek_shift=%s AND praktek_tgl=%s", [nik_pasien, nostr, username_dokter, kode_faskes, praktek_shift, praktek_tgl])
        row = dictfetchall(cursor)
        context = {
            'periksa':row[0],
        }
        return render(request, 'updateappointment.html', context)

def deleteappointment(request, nik_pasien, nostr, username_dokter, kode_faskes, praktek_shift, praktek_tgl):
    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM memeriksa WHERE nik_pasien=%s AND nostr=%s AND username_dokter=%s AND kode_faskes=%s AND praktek_shift=%s AND praktek_tgl=%s", [nik_pasien, nostr, username_dokter, kode_faskes, praktek_shift, praktek_tgl])
        return redirect('trigger2:listAppointment')

# nomor 6
def listRuanganRS(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM ruangan_rs")
        row = dictfetchall(cursor)
        context = {
            'list': row,
        }
    return render(request, 'listRuanganRS.html', context)

def listBedRs(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT b.koders, b.koderuangan, b.kodebed FROM bed_rs b, reservasi_rs r WHERE b.koders = r.koders AND b.koderuangan = r.koderuangan AND b.kodebed = r.kodebed AND r.tglkeluar < now()")
        tanggal = dictfetchall(cursor)
        cursor.execute("SELECT b.koders, b.koderuangan, b.kodebed FROM bed_rs b, reservasi_rs r WHERE b.koders = r.koders AND b.koderuangan = r.koderuangan AND b.kodebed = r.kodebed AND r.tglkeluar > now()")
        row = dictfetchall(cursor)
        cursor.execute("(SELECT b.koders, b.koderuangan, b.kodebed FROM bed_rs b) EXCEPT (select a.koders, a.koderuangan, a.kodebed from reservasi_rs a)")
        r = dictfetchall(cursor)
        context = {
            'list': row,
            'tgldelete':tanggal,
            'lis':r
        }
    return render(request, 'listBedRS.html', context)

def updateRuanganRS(request, koders, koderuangan):
    if request.method == 'POST':
        with connection.cursor() as cursor:
            tipe = request.POST.get('tipe')
            harga = request.POST.get('harga')
            cursor.execute("UPDATE ruangan_rs SET tipe=%s, harga=%s WHERE koders=%s AND koderuangan=%s" ,[tipe, harga, koders, koderuangan])
            return redirect("trigger2:listRuanganRS")

    with connection.cursor() as cursor:
        cursor.execute("SELECT * from ruangan_rs WHERE koders=%s AND koderuangan=%s",[koders, koderuangan])
        row = dictfetchall(cursor)
        context = {
            'ruang': row[0],
        }
    return render(request, 'updateRuanganRS.html', context)

def deleteBedRS(request, koders, koderuangan, kodebed):
    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM bed_rs WHERE koders=%s AND koderuangan=%s AND kodebed=%s", [koders, koderuangan, kodebed])
        return redirect('trigger2:listBedRs')

def createRuanganRS(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT kode_faskes FROM rumah_sakit")
        choice =  [(_[0], _[0]) for _ in cursor.fetchall()]
        
        if request.method == 'POST':
            data = request.POST.get('koders')
            return redirect("/ruang/" + data)

        form = CreateRuanganForm(choice)
        context = {
                'form' : form,
            }
        return render(request, 'createRuanganRS.html', context)

def ruang(request, koders):
    with connection.cursor() as cursor:
        cursor.execute(" SELECT split_part( max(koderuangan) :: TEXT, 'R', 2) FROM ruangan_rs ")
        str = cursor.fetchone()
        s = str[0]
        print(s)
        a = int(s)
        print(a)
        b = a + 1
        print(b)
        converted_num = "% s" % b
        d = len( converted_num)
        if d == 1:
            hasil = 'R0' +  converted_num
        else:
            hasil = 'R' +  converted_num

        context = {
            'koders': koders,
            'kode':hasil,
        }
        return render(request, 'ruang.html', context)

def hasilruang(request, koders, koderuangan):
    if request.method == 'POST':
        with connection.cursor() as cursor:
            tipe = request.POST.get('tipe')

trigger2/templates/buatAppointment.html
{% extends "base.html" %} {%load static%} 
{% block content %}
<div class="container mt-5 pt-5 mb-5">
  <h2 style="text-align: center;">FORM CREATE APPOINTMENT</h2>
  <form method="post" action="{% url 'trigger2:buatappointment' nostr=periksa.nostr username_dokter=periksa.username kode_faskes=periksa.kode_faskes praktek_shift=periksa.shift praktek_tgl=periksa.tanggal %}">
    {% csrf_token %}
    
    <div class="form-group">
      <label for="koders">NIK Pasien</label>
      {% for f in form %}
      <select name="koders" id='rskode' class="form-control" required>
        <option selected>pilih nik pasien</option>
        <option value="{{f}}"></option>
      </select>
      {% endfor %}
    </div>  

    <div class="form-group">
        <label for="username_dokter">Email Dokter</label>
        <input class="form-control" id="username_dokter" name="username_dokter" type="text" value="{{periksa.username}}" required disabled>
    </div>
    <div class="form-group">
        <label for="kode_faskes">Kode Faskes</label>
        <input class="form-control" id="kode_faskes" name="kode_faskes" type="text" value="{{periksa.kode_faskes}}" required disabled>
    </div>
    <div class="form-group">
        <label for="praktek_tgl">Tanggal Praktek</label>
        <input class="form-control" id="praktek_tgl" name="praktek_tgl" type="text" value="{{periksa.tanggal}}" required disabled>
    </div>
    <div class="form-group">
        <label for="praktek_shift">Shift Praktek</label>
        <input class="form-control" id="praktek_shift" name="praktek_shift" type="text" value="{{periksa.shift}}" required disabled>
    </div>
    <div class="d-flex justify-content-center">
      <button type="submit" class="btn btn-primary col-12">CREATE</button>
    </div>
  </form>
</div>
{% endblock content %}

trigger2/templates/createAppointment.html
{% extends "base.html" %} {%load static%} 
{% block content %}
<div class="container mt-5 pt-5 mb-5">
  <h2>Jadwal Dokter</h2>
  <br>
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{message.tags}} fade show" role="alert">
        {{message}}
      </div>
    {% endfor %}
  {% endif %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">No STR</th>
        <th scope="col">Email Dokter</th>
        <th scope="col">Faskes</th>
        <th scope="col">Shift</th>
        <th scope="col">Tanggal</th>
        <th scope="col">Create Appointment</th>
      </tr>
    </thead>
    <tbody>
      {%for row in jadwal%}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{row.nostr}}</td>
        <td>{{row.username}}</td>
        <td>{{row.kode_faskes}}</td>
        <td>{{row.shift}}</td>
        <td>{{row.tanggal}}</td>
        <td>
          <a href="{% url 'trigger2:buatappointment' nostr=row.nostr username_dokter=row.username kode_faskes=row.kode_faskes praktek_shift=row.shift praktek_tgl=row.tanggal %}">
              <button type="button" class="btn btn-outline-primary">Book</button>
          </a>
        </td>
      </tr>
      {%endfor%}
    </tbody>
  </table>
</div>
{% endblock content %}

trigger2/templates/createBdRS.html
{% extends "base.html" %} {%load static%} 
{% block content %}
<div class="container mt-5 pt-5 mb-5">
  <h2 style="text-align: center;">FORM CREATE BED RS</h2>
  <form method="post" action="{% url 'trigger2:createBedRS' %}">
    {% csrf_token %}

    <div class="form-group">
        <label for="koders">Kode Rumah Sakit</label>
        {% for f in form %}
        <select name="koders" id='rskode' class="form-control" required>
          <option selected>pilih kode rs</option>
          <option value="{{f}}"></option>
        </select>
        {% endfor %}
    </div>  

    <div class="form-group">
        <label for="koderuangan">Kode Ruangan</label>
        <select name="koderuangan" class="form-control" id="koderuangan"  required>
            <option selected>pilih kode ruangan</option>
            <option value="" ></option>
        </select>
    </div>  

    <div class="form-group">
        <label for="tipe">Kode Bed</label>
        <input class="form-control" name="kode_bed" id="kode_bed" type="text" value="" disabled required>
        <input type="hidden" id="custId" name="custId" value="">
    </div>

    <br>
    <div class="d-flex">
      <button type="submit" class="btn btn-primary col-12">Create</button>
    </div>
  </form>
</div>

<script src="{% static 'js/bed.js' %}" type="text/javascript"></script
{% endblock content %}

trigger2/templates/createJadwalDokter.html
{% extends "base.html" %} {%load static%} 
{% block content %}
<div class="container mt-5 pt-5 mb-5">
  <h2 style="text-align: center;">CREATE JADWAL DOKTER</h2>
  <br />
  <table class="table">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">Kode Faskes</th>
        <th scope="col">Shift</th>
        <th scope="col">Tanggal</th>
        <th scope="col">Create Jadwal Dokter</th>
      </tr>
    </thead>
    <tbody>
      {%for row in jadwal%}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{row.kode_faskes}}</td>
        <td>{{row.shift}}</td>
        <td>{{row.tanggal}}</td>
        <td>
          <a href="{% url 'trigger2:createJadwal' kode_faskes=row.kode_faskes shift=row.shift tanggal=row.tanggal %}">
              <button type="button" class="btn btn-outline-primary">Create</button>
          </a>
        </td>
      </tr>
      {%endfor%}
    </tbody>
  </table>
</div>
{% endblock content %}

trigger2/templates/createRuanganRS.html
{% extends "base.html" %} {%load static%} 
{% block content %}
<div class="container mt-5 pt-5 mb-5">
  <h2 style="text-align: center;">FORM CREATE RUANGAN RS</h2>
  <form method="post" action="{% url 'trigger2:createRuanganRS' %}">
    {% csrf_token %}
    <!-- <label >Kode Rumah Sakit</label>
    {% for field in form %}
    <div class="form-control" >
      {{ field }}
    </div>
    {% endfor %} -->

    <div class="form-group">
      <label for="koders">Kode Rumah Sakit</label>
      {% for f in form %}
      <select name="koders" id='rskode' class="form-control" required>
        <option selected>pilih kode rs</option>
        <option value="{{f}}"></option>
      </select>
      {% endfor %}
    </div>  

    <div class="d-flex">
      <button type="submit" class="btn btn-primary">Pilih</button>
    </div>
  </form>
</div>
{% endblock content %}

trigger2/templates/listAppointment.html
{% extends "base.html" %} {%load static%} 
{% block content %}
<div class="container mt-5 pt-5 mb-5">
  <h2>List Appointment</h2>
  <br />
  <table class="table">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">NIK Pasien</th>
        <th scope="col">Email Dokter</th>
        <th scope="col">Faskes</th>
        <th scope="col">Shift</th>
        <th scope="col">Tanggal</th>
        <th scope="col">Rekomendasi</th>
        {% if request.session.type == 'adminSatgas' or request.session.type == 'dokter' %}
        <th scope="col">Action</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {%for row in list_periksa%}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{row.nik_pasien}}</td>
        <td>{{row.username_dokter}}</td>
        <td>{{row.kode_faskes}}</td>
        <td>{{row.praktek_shift}}</td>
        <td>{{row.praktek_tgl}}</td>
        <td>{{row.rekomendasi}}</td>
        {% if request.session.type == 'dokter' %}
        <td> 
          <a href="{% url 'trigger2:updateappointment' nik_pasien=row.nik_pasien nostr=row.nostr username_dokter=row.username_dokter kode_faskes=row.kode_faskes praktek_shift=row.praktek_shift praktek_tgl=row.praktek_tgl %}">
            <button class="btn btn-outline-primary">Update</button>
          </a>
        </td>
        {% endif %}
        {% if request.session.type == 'adminSatgas' %}
        <td> 
          <a href="{% url 'trigger2:deleteappointment' nik_pasien=row.nik_pasien nostr=row.nostr username_dokter=row.username_dokter kode_faskes=row.kode_faskes praktek_shift=row.praktek_shift praktek_tgl=row.praktek_tgl %}">
            <button class="btn btn-outline-danger">Delete</button>
          </a>
        </td>
        {% endif %}
      </tr>
      {%endfor%}
    </tbody>
  </table>
</div>
{% endblock content %}

trigger2/templates/listBedRS.html
{% extends "base.html" %} {%load static%} 
{% block content %}
<div class="container mt-5 pt-5 mb-5">
  <h2>List Bed Rumah Sakit</h2>
  <br />
  <table class="table">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">Kode RS</th>
        <th scope="col">Kode Ruangan</th>
        <th scope="col">Kode Bed</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {%for r in tgldelete%}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{r.koders}}</td>
        <td>{{r.koderuangan}}</td>
        <td>{{r.kodebed}}</td>
        <td>
          <a href="{% url 'trigger2:deleteBedRS' koders=r.koders koderuangan=r.koderuangan kodebed=r.kodebed %}">
            <button type="button" class="btn btn-outline-danger">delete</button>
          </a>  
        </td>
      </tr>
      {%endfor%}
      {%for row in lis%}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{row.koders}}</td>
        <td>{{row.koderuangan}}</td>
        <td>{{row.kodebed}}</td>
        <td></td>
      </tr>
      {%endfor%}
      {%for row in list%}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{row.koders}}</td>
        <td>{{row.koderuangan}}</td>
        <td>{{row.kodebed}}</td>
        <td></td>
      </tr>
      {%endfor%}
    </tbody>
  </table>
</div>
{% endblock content %}

trigger2/templates/listRuanganRS.html
{% extends "base.html" %} {%load static%} 
{% block content %}
<div class="container mt-5 pt-5 mb-5">
  <h2>List Ruangan Rumah Sakit</h2>
  <br />
  <table class="table">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">Kode RS</th>
        <th scope="col">Kode Ruangan</th>
        <th scope="col">Tipe</th>
        <th scope="col">Jumlah Bed</th>
        <th scope="col">Harga Ruangan</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {%for row in list%}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{row.koders}}</td>
        <td>{{row.koderuangan}}</td>
        <td>{{row.tipe}}</td>
        <td>{{row.jmlbed}}</td>
        <td>{{row.harga}}</td>
        <td>
          <a href="{% url 'trigger2:updateRuanganRS' koders=row.koders koderuangan=row.koderuangan%}">
            <button type="button" class="btn btn-outline-primary">Update</button>
          </a>
        </td>
      </tr>
      {%endfor%}
    </tbody>
  </table>
</div>
{% endblock content %}

trigger2/templates/ruang.html
{% extends "base.html" %} {%load static%} 
{% block content %}
<div class="container mt-5 pt-5 mb-5">
  <h2 style="text-align: center;">FORM CREATE RUANGAN RS</h2>
  <form method="post" action="{% url 'trigger2:hasilruang' koders=koders koderuangan=kode%}">
    {% csrf_token %}
    <div class="form-group">
        <label for="koders">Kode Rumah Sakit</label>
        <input class="form-control" id="koders" name="koders" type="text" value="{{koders}}" disabled>
    </div>
    <div class="form-group">
        <label for="koderuangan">Kode Ruangan</label>
        <input class="form-control" id="koderuangan" name="koderuangan" type="text" value="{{kode}}" disabled>
    </div>
    <div class="form-group">
        <label for="tipe">Tipe</label>
        <input class="form-control" id="tipe" name="tipe" type="text" required>
    </div>
    <div class="form-group">
        <label for="harga">Harga Ruangan</label>
        <input class="form-control" id="harga" name="harga" type="text" required>
    </div>
    <br>
    <div class="d-flex">
      <button type="submit" class="btn btn-primary col-12">Pilih</button>
    </div>
  </form>
</div>
{% endblock content %}

trigger2/templates/updateRuanganRS.html
{% extends "base.html" %} {%load static%} 
{% block content %}
<div class="container mt-5 pt-5 mb-5">
  <h2 style="text-align: center;">FORM UPDATE RUANGAN RS</h2>
  <form method="POST" action="{% url 'trigger2:updateRuanganRS' koders=ruang.koders koderuangan=ruang.koderuangan %}">
    {% csrf_token %}
      <div class="form-group">
          <label for="koders">Kode Rumah Sakit</label>
          <input class="form-control" id="koders" name="koders" type="text" disabled value={{ruang.koders}}>
      </div>
      <div class="form-group">
          <label for="koderuangan">Kode Ruangan</label>
          <input class="form-control" id="koderuangan" name="koderuangan" type="text" disabled value={{ruang.koderuangan}}>
      </div>
      <div class="form-group">
          <label for="tipe">Tipe</label>
          <input class="form-control" id="tipe" name="tipe" type="text" value={{ruang.tipe}} required>
      </div>
      <div class="form-group">
          <label for="harga">Harga Ruangan</label>
          <input class="form-control" id="harga" name="harga" type="text" value={{ruang.harga}} required>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock content %}